#!/bin/bash

function init {
	wall_dir=~/Pictures/Wallpaper
	file_name="`date +%s`.jpg"
	wall_file="$wall_dir/wallpaper.jpg"
	client_id="cd9c86576780cb44370a73dede11f761485dd3fa03fe3ac3582be37adf29e431"
}

function get_file {
	a=`curl "https://api.unsplash.com/photos/random/?client_id=$client_id" | jq \
	.urls.full` 
	#remove trailing " from url
	a="${a%\"}"
	#remove beginning " from url
	a="${a#\"}"
	curl $a --output $file_name
}

function set_wall_linux {
	mv "`pwd`/$file_name" "$wall_file"
	DISPLAY=:0 feh --bg-scale $wall_file
}

#to be done when I have access to a Mac
function set_wall_mac {
	echo "Mac support coming soon!"
	osascript <<EOD
		tell application "System Events"
			tell current desktop
				set picture rotation to 0
				set picture to file       -- incomplete
			end tell
		end tell
EOD
}

function set_wall {
	case "$OSTYPE" in
		linux*)		set_wall_linux;;
		darwin*)	set_wall_mac;;
		*)			echo "Unsupported OS";;
	esac
}

init
get_file
set_wall
